//
//  Pantalla1Router.swift
//  PantallasCleanSwift
//
//  Created by Adrian on 24-05-22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol Pantalla1RoutingLogic
{
  func routeToPantalla2(segue: UIStoryboardSegue?)
}

protocol Pantalla1DataPassing
{
  var dataStore: Pantalla1DataStore? { get }
}

class Pantalla1Router: NSObject, Pantalla1RoutingLogic, Pantalla1DataPassing
{
  weak var viewController: Pantalla1ViewController?
  var dataStore: Pantalla1DataStore?
  
  // MARK: Routing
  
  func routeToPantalla2(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! Pantalla2ViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToPatalla2(source: dataStore!, destination: &destinationDS)
    } else {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "Pantalla2ViewController") as! Pantalla2ViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToPatalla2(source: dataStore!, destination: &destinationDS)
      navigateToPantalla2(source: viewController!, destination: destinationVC)
    }
  }

  // MARK: Navigation
  
  func navigateToPantalla2(source: Pantalla1ViewController, destination: Pantalla2ViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToPatalla2(source: Pantalla1DataStore, destination: inout Pantalla2DataStore)
  {
      destination.datosRecibidos = source.datosEnviados
  }
}
