//
//  Pantalla1Worker.swift
//  PantallasCleanSwift
//
//  Created by Adrian on 24-05-22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class Pantalla1Worker
{
    var nombreReal: String = "Adrian"
    var claveReal: String = "123456"
    
    func doSomeWork(request: Pantalla1.Something.Request) -> Bool {
        if (self.nombreReal == request.loginRequest && self.claveReal == request.passwordRequest){
            return true
        }else {return false}
    }
}
