//
//  Pantalla1Models.swift
//  PantallasCleanSwift
//
//  Created by Adrian on 24-05-22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Pantalla1
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
        var loginRequest: String
        var passwordRequest: String
    }
    struct Response
    {
        var nombreResponse: String
        var passwordResponse: String
        var validacion: Bool
    }
    struct ViewModel
    {
        var nombreVM: String
        var passwordVM: String
        var validacionVM: Bool
    }
  }
}
