//
//  Pantalla1Interactor.swift
//  PantallasCleanSwift
//
//  Created by Adrian on 24-05-22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Pantalla1BusinessLogic
{
  func doSomething(request: Pantalla1.Something.Request)
}

protocol Pantalla1DataStore
{
  //var name: String { get set }
}

class Pantalla1Interactor: Pantalla1BusinessLogic, Pantalla1DataStore
{
  var presenter: Pantalla1PresentationLogic?
  var worker: Pantalla1Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Pantalla1.Something.Request)
  {
    worker = Pantalla1Worker()
    worker?.doSomeWork()
    
    let response = Pantalla1.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
