//
//  Pantalla2Models.swift
//  PantallasCleanSwift
//
//  Created by Adrian on 24-05-22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Pantalla2
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
        var nombreResponseP2: String
        var passwordResponseP2: String
    }
    struct ViewModel
    {
        var nombreVMP2: String
        var passwordVMP2: String
    }
  }
}
