//
//  Pantalla2Presenter.swift
//  PantallasCleanSwift
//
//  Created by Adrian on 24-05-22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Pantalla2PresentationLogic
{
  func presentSomething(response: Pantalla2.Something.Response)
}

class Pantalla2Presenter: Pantalla2PresentationLogic
{
  weak var viewController: Pantalla2DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Pantalla2.Something.Response)
  {
      let viewModel = Pantalla2.Something.ViewModel(nombreVMP2: response.nombreResponseP2, passwordVMP2: response.passwordResponseP2)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
